--
-- PostgreSQL database dump
--

-- Dumped from database version 16.8 (Debian 16.8-1.pgdg120+1)
-- Dumped by pg_dump version 17.0

-- Started on 2025-03-29 17:32:53

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: easyui_d90k_user
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO easyui_d90k_user;

--
-- TOC entry 3430 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: easyui_d90k_user
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16426)
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: easyui_d90k_user
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetRoleClaims" OWNER TO easyui_d90k_user;

--
-- TOC entry 219 (class 1259 OID 16425)
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: easyui_d90k_user
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16411)
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: easyui_d90k_user
--

CREATE TABLE public."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE public."AspNetRoles" OWNER TO easyui_d90k_user;

--
-- TOC entry 222 (class 1259 OID 16439)
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: easyui_d90k_user
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetUserClaims" OWNER TO easyui_d90k_user;

--
-- TOC entry 221 (class 1259 OID 16438)
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: easyui_d90k_user
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16451)
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: easyui_d90k_user
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


ALTER TABLE public."AspNetUserLogins" OWNER TO easyui_d90k_user;

--
-- TOC entry 224 (class 1259 OID 16463)
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: easyui_d90k_user
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


ALTER TABLE public."AspNetUserRoles" OWNER TO easyui_d90k_user;

--
-- TOC entry 225 (class 1259 OID 16480)
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: easyui_d90k_user
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


ALTER TABLE public."AspNetUserTokens" OWNER TO easyui_d90k_user;

--
-- TOC entry 218 (class 1259 OID 16418)
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: easyui_d90k_user
--

CREATE TABLE public."AspNetUsers" (
    "Id" text NOT NULL,
    "FullName" text,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE public."AspNetUsers" OWNER TO easyui_d90k_user;

--
-- TOC entry 216 (class 1259 OID 16404)
-- Name: UIComponents; Type: TABLE; Schema: public; Owner: easyui_d90k_user
--

CREATE TABLE public."UIComponents" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL
);


ALTER TABLE public."UIComponents" OWNER TO easyui_d90k_user;

--
-- TOC entry 215 (class 1259 OID 16399)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: easyui_d90k_user
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO easyui_d90k_user;

--
-- TOC entry 3419 (class 0 OID 16426)
-- Dependencies: 220
-- Data for Name: AspNetRoleClaims; Type: TABLE DATA; Schema: public; Owner: easyui_d90k_user
--



--
-- TOC entry 3416 (class 0 OID 16411)
-- Dependencies: 217
-- Data for Name: AspNetRoles; Type: TABLE DATA; Schema: public; Owner: easyui_d90k_user
--



--
-- TOC entry 3421 (class 0 OID 16439)
-- Dependencies: 222
-- Data for Name: AspNetUserClaims; Type: TABLE DATA; Schema: public; Owner: easyui_d90k_user
--



--
-- TOC entry 3422 (class 0 OID 16451)
-- Dependencies: 223
-- Data for Name: AspNetUserLogins; Type: TABLE DATA; Schema: public; Owner: easyui_d90k_user
--



--
-- TOC entry 3423 (class 0 OID 16463)
-- Dependencies: 224
-- Data for Name: AspNetUserRoles; Type: TABLE DATA; Schema: public; Owner: easyui_d90k_user
--



--
-- TOC entry 3424 (class 0 OID 16480)
-- Dependencies: 225
-- Data for Name: AspNetUserTokens; Type: TABLE DATA; Schema: public; Owner: easyui_d90k_user
--



--
-- TOC entry 3417 (class 0 OID 16418)
-- Dependencies: 218
-- Data for Name: AspNetUsers; Type: TABLE DATA; Schema: public; Owner: easyui_d90k_user
--



--
-- TOC entry 3415 (class 0 OID 16404)
-- Dependencies: 216
-- Data for Name: UIComponents; Type: TABLE DATA; Schema: public; Owner: easyui_d90k_user
--

INSERT INTO public."UIComponents" VALUES ('93abce9c-a22f-40ed-b5d0-d9d850d31657', 'tiến');


--
-- TOC entry 3414 (class 0 OID 16399)
-- Dependencies: 215
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: easyui_d90k_user
--

INSERT INTO public."__EFMigrationsHistory" VALUES ('20250328165028_init-postgre', '9.0.3');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20250328180416_Init_Identity', '9.0.3');


--
-- TOC entry 3431 (class 0 OID 0)
-- Dependencies: 219
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: easyui_d90k_user
--

SELECT pg_catalog.setval('public."AspNetRoleClaims_Id_seq"', 1, false);


--
-- TOC entry 3432 (class 0 OID 0)
-- Dependencies: 221
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: easyui_d90k_user
--

SELECT pg_catalog.setval('public."AspNetUserClaims_Id_seq"', 1, false);


--
-- TOC entry 3253 (class 2606 OID 16432)
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: easyui_d90k_user
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- TOC entry 3245 (class 2606 OID 16417)
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: easyui_d90k_user
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- TOC entry 3256 (class 2606 OID 16445)
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: easyui_d90k_user
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- TOC entry 3259 (class 2606 OID 16457)
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: easyui_d90k_user
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- TOC entry 3262 (class 2606 OID 16469)
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: easyui_d90k_user
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- TOC entry 3264 (class 2606 OID 16486)
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: easyui_d90k_user
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- TOC entry 3249 (class 2606 OID 16424)
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: easyui_d90k_user
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- TOC entry 3243 (class 2606 OID 16410)
-- Name: UIComponents PK_UIComponents; Type: CONSTRAINT; Schema: public; Owner: easyui_d90k_user
--

ALTER TABLE ONLY public."UIComponents"
    ADD CONSTRAINT "PK_UIComponents" PRIMARY KEY ("Id");


--
-- TOC entry 3241 (class 2606 OID 16403)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: easyui_d90k_user
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3247 (class 1259 OID 16497)
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: easyui_d90k_user
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- TOC entry 3251 (class 1259 OID 16492)
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: easyui_d90k_user
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- TOC entry 3254 (class 1259 OID 16494)
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: easyui_d90k_user
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- TOC entry 3257 (class 1259 OID 16495)
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: easyui_d90k_user
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- TOC entry 3260 (class 1259 OID 16496)
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: easyui_d90k_user
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- TOC entry 3246 (class 1259 OID 16493)
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: easyui_d90k_user
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- TOC entry 3250 (class 1259 OID 16498)
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: easyui_d90k_user
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- TOC entry 3265 (class 2606 OID 16433)
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: easyui_d90k_user
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3266 (class 2606 OID 16446)
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: easyui_d90k_user
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3267 (class 2606 OID 16458)
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: easyui_d90k_user
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3268 (class 2606 OID 16470)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: easyui_d90k_user
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3269 (class 2606 OID 16475)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: easyui_d90k_user
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3270 (class 2606 OID 16487)
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: easyui_d90k_user
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


-- Completed on 2025-03-29 17:33:22

--
-- PostgreSQL database dump complete
--

